### PR TITLE
Added specifications section for FIDO

### PR DESCRIPTION
**Pull request by harhitosw**
Added a section only for original specifications which will help user to navigate to right place. I am not really sure is this needed or not but since this list has everything encompassing WebAuthn and FIDO this can also be a value addition. Please feel free to make changes !

### CODE REVIEW

**Comment by harhitosw** [comment]
I have also added an article link for being Microsoft compatible FIDO security key vendor if it is important.

**Comment by yackermann** [comment]
@harhitosw maybe change FIDO2 spec to actual latest CTAP2.1 PS

And add webatuhn editorial draft. Thx

**Comment by harhitosw** [comment]
> @harhitosw maybe change FIDO2 spec to actual latest CTAP2.1 PS
> 
> And add webatuhn editorial draft. Thx

@yackermann added respective links in the latest commit of same PR . Mergeable now.

**Comment by yackermann** [comment]
@harhitosw WebAuthn still wrong, should be https://w3c.github.io/webauthn/

**Comment by yackermann** [comment]
And its `WebAuthn` not `WebAuthN`

**Pull request closed without merging**
